---
name: Push
on:
  push:
    branches:
      - master
      - abort-result-fix-test
    tags-ignore:
      - '**'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:

      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DNAME }}
          password: ${{ secrets.DPASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/Dockerfile
          platforms: linux/amd64
          tags: avaakash/go-runner:abort-result